[package]
name = "ti-project"
version = "0.1.0"
edition = "2021"

[features]
verify = []
no_lcp = []

[profile.release]
debug = true

[dependencies]
divsufsort = "2.0.0"

[build-dependencies]
cc = "1.0"
